name: sos_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Hashes and Encryption
  rsa_encrypt: ^2.0.0
  encrypt: ^5.0.1

  file_picker: ^4.1.6
  fluttercontactpicker: ^4.5.1
  fluttertoast: ^8.0.8
  google_fonts: 2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  sliding_switch: ^1.0.0

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  firebase_storage: ^10.1.0
  firebase_database: ^9.0.4

  # Save data locally
  shared_preferences: ^2.0.10
  sqflite: ^2.0.2
  path: ^1.8.0

  # Sensors
  geolocator: ^7.7.1
  weather: ^2.0.1
  sensors: ^2.0.3
  shimmer:
  auto_route: ^3.0.1
  camera: ^0.9.4+3
  battery: ^2.0.3

  # Health parsers
  health: ^3.3.1

  # Calling dep
  flutter_phone_direct_caller: ^2.0.0

  # Video streaming dep
  permission_handler: ^8.3.0

  # Video Stream
  flutter_webrtc:  ^0.8.1

  # Background services
  flutter_background_service: ^0.2.2

  # Notifications
  flutter_local_notifications: ^9.2.0

  # DateTime
  intl: ^0.17.0

  # Stopwatch
  stop_watch_timer: ^1.3.1

dependency_overrides:
  auto_route:
    git:
      url: https://github.com/Agondev/auto_route_library
      path: auto_route

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
      - assets/images/CameraPlaceholder.jpg
      - assets/images/SoundwavePlaceholder.png
      - assets/images/HowToUsePlaceholder.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
